### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by MahdiYahia** [BME-MIT-IET/ivt-hw-2023-mega-bite#4]
I chose to perform the Static Analysis using SonarQube.

#The first step of my work will be installing SonarQube.
>> SonarQube and sonar-scanner were installed successfully and the first analysis was run.

**Comment by MahdiYahia** [comment]
#Second step will be the review of problems detected by the first analysis.

**Comment by MahdiYahia** [comment]
#Code reviewed and overview of SonarQube written.

**Comment by MahdiYahia** [comment]
#9

**Comment by DHoussama** [comment]
Good Work
